export const ADD_CAKE_TO_CART = "ADD_TO_CART";
export const REMOVE_CAKE_FROM_CART = "REMOVE_FROM_CART";
export const CHECKOUT = "CHECKOUT";

export const APPLY_SEARCH_PARAMS = "APPLY_SEARCH_PARAMS";
export const ADD_CAKE_TO_STORE = "ADD_CAKE_TO_STORE";
export const UPDATE_CAKE_IN_STORE = "UNDATE_CAKE_IN_STORE";
export const REMOVE_CAKE_FROM_STORE = "REMOVE_CAKE_FROM_STORE";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const ADD_POST = "ADD_POST";
export const CHANGE_PROFILE_DATA = "CHANGE_PROFILE_DATA";

export const CHANGE_SEARCH_TYPE = "CHANGE_SEARCH_TYPE";
export const SEARCH_BY_SEARCH_TERM = "SEARCH_BY_SEARCH_TERM";
export const SEARCH_BY_CATEGORY = "SEARCH_BY_CATEGORY";
export const SORT_BY = "SORT_BY";

export const ERROR_FOUND = "ERROR_FOUND";
export const SWITCH_THE_THEME = "SWITCH_THE_THEME";

export const SWITCH_TO_NARROW_SCREEN_MODE = "SWITCH_TO_NARROW_SCREEN_MODE";
export const SWITCH_TO_WIDE_SCREEN_MODE = "SWITCH_TO_WIDE_SCREEN_MODE";
export const TOGGLE_NAVIGATION = "TOGGLE_NAVIGATION";